name: Next.js CI/CD

on:
  push:
    branches: ["develop"]
  pull_request:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3. Dependencies install
      - name: Install dependencies
        run: npm install

      # 4. Build Next.js
      - name: Build Next.js
        run: npm run build

      # 5. Run tests (optional)
      # - name: Run tests
      #   run: npm test

      # 6. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest .

      # 8. Push Docker image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest
