name: Next.js CI/CD

on:
  push:
    branches: ["develop"]
  pull_request:

jobs:
  build:
    name: Build Next.js
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node setup with caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests (optional - add if you have tests)
      - name: Run tests
        run: npm test

      # 5. Build Next.js
      - name: Build Next.js
        run: npm run build

      # 6. Upload build artifacts (for Docker job)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --audit-level=high

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: [build, security-scan]
    steps:
      - name: Development deploy step
        run: |
          echo "Deploying to development..."
          sleep 5s
          echo "Deployment complete!"

  docker-publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [deploy-dev]

    steps:
      # 1. Checkout repo (needed for Docker context)
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Download Next.js build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: next-build

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and push Docker image with caching
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest
